-- Insert luxury skincare products
INSERT INTO products (name, description, price, category, subcategory, image_url, benefits, ingredients, how_to_use, size, featured, stock_quantity) VALUES
(
  'Luminous Radiance Serum',
  'An advanced brightening serum infused with 24k gold particles and vitamin C for unparalleled radiance.',
  189.99,
  'Skincare',
  'Serums',
  'https://images.pexels.com/photos/6621461/pexels-photo-6621461.jpeg',
  ARRAY['Brightens complexion', 'Reduces dark spots', 'Enhances skin luminosity', 'Improves skin texture'],
  ARRAY['24k Gold Particles', 'Stabilized Vitamin C', 'Niacinamide', 'Hyaluronic Acid', 'Pearl Extract'],
  'Apply 2-3 drops to cleansed face and neck, morning and evening. Follow with moisturizer.',
  '30ml',
  true,
  50
),
(
  'Royal Renewal Night Cream',
  'A luxurious overnight treatment enriched with rare botanical extracts and peptides.',
  245.00,
  'Skincare',
  'Moisturizers',
  'https://images.pexels.com/photos/6621264/pexels-photo-6621264.jpeg',
  ARRAY['Intensive hydration', 'Skin regeneration', 'Fine line reduction', 'Enhanced elasticity'],
  ARRAY['Snow Algae Extract', 'Advanced Peptide Complex', 'Ceramides', 'Squalane', 'Rose Essential Oil'],
  'Apply generously to face and neck before bedtime. Massage in upward motions.',
  '50ml',
  true,
  35
),
(
  'Velvet Matte Lip Elixir',
  'A weightless, long-wearing liquid lipstick with a sophisticated matte finish.',
  85.00,
  'Makeup',
  'Lips',
  'https://images.pexels.com/photos/2688992/pexels-photo-2688992.jpeg',
  ARRAY['8-hour wear', 'Non-drying formula', 'Intense color payoff', 'Comfortable wear'],
  ARRAY['Jojoba Oil', 'Vitamin E', 'Collagen Spheres', 'Natural Pigments'],
  'Apply to clean, dry lips using the precision applicator. Allow to set for 30 seconds.',
  '6ml',
  true,
  75
),
(
  'Golden Hour Illuminating Oil',
  'A luxurious dry oil that imparts a subtle, golden shimmer to skin and hair.',
  165.00,
  'Body Care',
  'Body Oils',
  'https://images.pexels.com/photos/6621329/pexels-photo-6621329.jpeg',
  ARRAY['Multi-purpose use', 'Subtle illumination', 'Deep nourishment', 'Non-greasy finish'],
  ARRAY['Argan Oil', 'Camellia Oil', 'Gold Mica', 'Vitamin E', 'Evening Primrose Oil'],
  'Apply to damp skin after bathing or mist onto hair ends for extra shine.',
  '100ml',
  true,
  40
),
(
  'Eternal Youth Eye Complex',
  'An advanced eye treatment targeting multiple signs of aging with rare botanical extracts.',
  210.00,
  'Skincare',
  'Eye Care',
  'https://images.pexels.com/photos/6621441/pexels-photo-6621441.jpeg',
  ARRAY['Reduces dark circles', 'Minimizes fine lines', 'Depuffs eye area', 'Brightens eye contour'],
  ARRAY['Retinol', 'Caffeine', 'White Truffle Extract', 'Peptide Complex', 'Hyaluronic Acid'],
  'Gently pat around eye area morning and evening using ring finger.',
  '15ml',
  false,
  30
),
(
  'Rose Quartz Facial Essence',
  'A hydrating essence infused with rose quartz crystals and damask rose water.',
  135.00,
  'Skincare',
  'Essences',
  'https://images.pexels.com/photos/6621426/pexels-photo-6621426.jpeg',
  ARRAY['Deep hydration', 'Balances pH', 'Prepares skin', 'Calming properties'],
  ARRAY['Rose Quartz Extract', 'Damask Rose Water', 'Beta-Glucan', 'Panthenol', 'Niacinamide'],
  'After cleansing, pour into palms and press gently into skin.',
  '120ml',
  false,
  45
);
